name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published
      - deleted
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library.yml@4.x.y
    secrets: inherit

  cortex-m3:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.x.y
    with:
      profile: stm32f103c8
      upload: true
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  stm32f103c4:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.x.y
    with:
      profile: stm32f103c4
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  stm32f103zd:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.x.y
    with:
      profile: stm32f103zd
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit
