name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library.yml@4.0.0
    secrets: inherit

  cortex-m3:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: stm32f103c8
      upload: true
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  stm32f103c4:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: stm32f103c4
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  stm32f103zd:
    uses: libhal/ci/.github/workflows/platform_deploy.yml@4.0.0
    with:
      profile: stm32f103zd
      processor_profile: https://github.com/libhal/libhal-armcortex.git
    secrets: inherit

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
